### ISSUE TITLE
Microstutters since 2024

### ISSUE THREAD

**Issue by R-Bower** [AtomMaterialUI/a-file-icon-idea#449]
**Describe the bug**
Microstutters every half second in WebStorm 2024

**To Reproduce**

1. Install this plugin.
2. Try to navigate via the keyboard in an Angular component.

**Expected Behavior**
1. No lag or freezing.

**Environment**
WebStorm 2024.1.2
Build #WS-241.15989.105, built on April 23, 2024
You have a perpetual fallback license for this version.
Subscription is active until August 4, 2025.
Runtime version: 17.0.10+1-b1207.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.146.1-microsoft-standard-wsl2
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 32
Registry:
  undo.documentUndoLimit=1000
  actionSystem.playback.typecommand.delay=5
  ide.forcedShowTooltip=
  ide.balloon.shadow.size=0
  debugger.watches.in.variables=false
  debugger.new.tool.window.layout=true
  vcs.resolve.symlinks.for.vcs.operations=
  keymap.windows.as.meta=true
  ide.ui.tree.indent=4
  terminal.distraction.free=true
  toolwindow.disable.overlay.by.double.key=true
  ide.experimental.ui=true
  typescript.compiler.all.settings=true
  eslint.service.node.arguments=--max_old_space_size=8192
Non-Bundled Plugins:
  awesome.console (0.1337.12)
  com.jaredrobertson.plugins.angularFileSwitcher (0.0.8)
  lermitage.intellij.extra.icons (2024.3.4)
  ru.adelf.idea.dotenv (2024.1)
  com.intellij.database (241.14494.180)
  mdx.js (241.15989.9)
  com.mallowigi (95.0.0)
  zielu.gittoolbox (500.2.6+233)
  mobi.hsz.idea.gitignore (4.5.3)

**Screenshots**

![ide-slow](https://github.com/mallowigi/a-file-icon-idea/assets/11933208/dcbc78a4-2717-40f4-b7c7-62d34e269ac1)

**Comment by mallowigi** [comment]
Do you have a project I can reproduce?

**Comment by R-Bower** [comment]
> Do you have a project I can reproduce?

https://github.com/ng-doc/ng-doc

**Comment by RavenHursT** [comment]
Looks like maybe related to the same behavior I just reported here over in JetBrain's tracker and the Material UI plugin repo: 

https://youtrack.jetbrains.com/issue/WEB-66851/Keystrokes-in-latest-ver-of-WebStorm-SEVERELY-delayed
https://github.com/mallowigi/material-theme-issues/issues/508

**Comment by xDroni** [comment]
I have also been experiencing this problem for quite some time now.

**Comment by mallowigi** [comment]
Are you using custom VM options?

**Comment by RavenHursT** [comment]
No.

**Comment by mallowigi** [comment]
I really have no clue. I thought this would be -Dsun.java2d.metal=false causing the issue but it doesn't seem like you have it.

Is the problem happening also on a Factory Defaults setup?

**Comment by RavenHursT** [comment]
What do you mean "a Factory Defaults setup"? 🤔

**Comment by mallowigi** [comment]
I mean if you change the config directory from the toolbox to use a clean directory without any settings or plugins, and install the plugin, do you still experience slowness?

**Comment by R-Bower** [comment]
This only seems to impact me when I have multiple instances of WebStorm open. What could be causing this?

**Comment by R-Bower** [comment]
This issue seems to be resolved in 2024.2 EAP.  I'll keep testing and report back.

**Comment by mallowigi** [comment]
glad to hear

**Comment by mallowigi** [comment]
I'm encountering something similar in 2024.2 EAP...
