### ISSUE TITLE
The icon size of the "New Test from Test Cases" menu item is too big.

### ISSUE THREAD

**Issue by danny-su** [AtomMaterialUI/a-file-icon-idea#459]
Enable the “Test Management” plugin.
<img width="558" alt="image" src="https://github.com/user-attachments/assets/92c2a9a9-f389-4f88-9a08-b42221112693">

“Atom Material Icons” overwrites this icon. The original icon's size is normal.
<img width="664" alt="iShot Pro 2024-07-27 22 19 15" src="https://github.com/user-attachments/assets/94b27cbb-0a1f-4e5e-a179-0a661c04eab1">

**Comment by mallowigi** [comment]
Will be fixed next version
