### ISSUE TITLE
Terminal icon is very large

### ISSUE THREAD

**Issue by MPeloquin** [AtomMaterialUI/a-file-icon-idea#467]
**Describe the bug**

**To Reproduce**

1. Have webstorm 2023.1.6
2. Install plugin, might need to use my settings to repro:
[webstorm2023.2.zip](https://github.com/user-attachments/files/16896624/webstorm2023.2.zip)
3. Notice terminal icon is very large

**Expected Behavior**

Before icon was normal sized

**Environment**
WebStorm 2023.1.6
Build #WS-231.9423.2, built on June 4, 2024
Licensed to Maxime Peloquin
You have a perpetual fallback license for this version.
Subscription expired on June 19, 2024.
Runtime version: 17.0.10+10-b829.27 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 11
Metal Rendering is ON
Registry:
    ide.intellij.laf.enable.animation=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    be.jbeckers.compare_tab_with_editor2 (1.0.17)
    Rider UI Theme Pack (0.14.11)
    de.femtopedia.diffplugin (2.1.10)
    com.mallowigi (90.0.0)
    com.github.copilot (1.5.21.6667)
    com.intellij.lang.jsgraphql (4.0.1)

**Screenshots**

![CleanShot 2024-09-05 at 11 20 44](https://github.com/user-attachments/assets/d99b89c1-26e6-45df-9952-0dab4ab9f6a9)

**Comment by MPeloquin** [comment]
Closing, noticed newer versions are available, but since I'm on a old webstorm I can't update

**Comment by MPeloquin** [comment]
Note: if anyone has the same issue, I was able to fix by setting the icon size manually

![CleanShot 2024-09-12 at 17 49 30](https://github.com/user-attachments/assets/f991d929-8b0e-480f-8967-e0b6b2c2a941)

**Comment by mallowigi** [comment]
Keep it open. I have fixed it for the next version but I'm in the middle of a large feature and I can't release it now.
