### ISSUE TITLE
Patterns for TS file types in PHPStorm don't work properly

### ISSUE THREAD

**Issue by Jeko92** [AtomMaterialUI/a-file-icon-idea#468]
**Describe the bug**
TypeScript Icons In PHPStorm are not generated correctly

**To Reproduce**
1. Create TypeScript folder and inside it create following files: `FooBar.controller.ts`, `FooBar.component.ts`, `FooBar.model.ts, `FooBar.service.ts`, `FooBar.utils.ts` and you will see that icons generated are different than From TypeScript Icons.

**Expected Behavior**
Files created inside TypeScript folder to have a TS icon with different flavor(colors)

**Environment**
```
PhpStorm 2024.2.1
Build #PS-242.21829.154, built on August 29, 2024
Subscription is active until June 30, 2025.
Runtime version: 21.0.3+13-b509.11 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  run.processes.with.pty=TRUE
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  i18n.locale=
Non-Bundled Plugins:
  org.jetbrains.plugins.gitlab (242.21829.162)
  org.jetbrains.plugins.github (242.21829.162)
  com.chrisrm.idea.MaterialThemeUI (9.5.0)
  ru.adelf.idea.dotenv (2024.2.1)
  de.sgalinski.typoscript.enterprise.plugin.id (2.8.1)
  de.sgalinski.fluid.plugin.id (2.8.1)
  com.mallowigi (97.0.0)
```

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version
* If needed a list of enabled plugins -->

**Screenshots**
![Screenshot 2024-09-10 at 08 58 13](https://github.com/user-attachments/assets/5b37c90c-12e5-4a89-85d4-70bc610a023f)

![Screenshot 2024-09-10 at 09 01 48](https://github.com/user-attachments/assets/06ea100a-8ff7-4917-9000-93dc995a49ef)

I would definitely loved to contribute to this issue in case it will be considered as issue.

**Comment by mallowigi** [comment]
Disable the Angular and NestJS packs
