### ISSUE TITLE
Unable to display correct icons in page.tsx and layout.tsx files

### ISSUE THREAD

**Issue by oyal** [AtomMaterialUI/a-file-icon-idea#469]
**Describe the bug**

I hope to display the React icon in page.tsx and layout.tsx file.

![image](https://github.com/user-attachments/assets/3de60321-cc0d-4c08-8706-2db2e1103148)

**To Reproduce**

1. Create a page.tsx file.

**Expected Behavior**

Display the React icon in page.tsx and layout.tsx file.

**Environment**

WebStorm 2024.2.1
Build #WS-242.21829.149, built on August 29, 2024
授权给 Peacemaker Rachel
订阅有效期至 2025年3月25日。
For educational use only.
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  i18n.locale=
  vue.language.server.default.version=2.1.2
Non-Bundled Plugins:
  com.nasller.CodeGlancePro (1.9.1)
  Key Promoter X (2024.2.0)
  app.oyal.plugins.gitcommitmessagetool (1.0.0)
  org.jetbrains.plugins.gitlab (242.21829.162)
  org.jetbrains.plugins.github (242.21829.162)
  com.intellij.database (242.21829.149)
  com.github.copilot (1.5.24.6840)
  com.mallowigi (97.0.0)
  zielu.gittoolbox (600.0.1+242)
  mobi.hsz.idea.gitignore (4.5.3)
  cn.yiiguxing.plugin.translate (3.6.5)

**Screenshots**

**Comment by mallowigi** [comment]
Turn off the NextJS icon pack
