### ISSUE TITLE
Selected file color

### ISSUE THREAD

**Issue by eTaoss** [AtomMaterialUI/a-file-icon-idea#473]
**Describe the bug**
The color of the currently selected file in the "Project view" is same as the background. So it is impossible to see, which file is currently selected

**To Reproduce**

1. Open the file in phpstorm
2. open the project view
3. click the button to "Select Opened File" (round circle in circle icon in the top right of the project view
4. the opened file should be highlighted, but view is only scrolled and there is no highligting color for active file

**Expected Behavior**
Some color should be set to help differentiate the active file from the rest of the files

**Environment**
PhpStorm 2024.2.4
Build #PS-242.23726.107, built on October 23, 2024
Runtime version: 21.0.4+13-b509.26 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Mac os

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version
* If needed a list of enabled plugins -->

**Screenshots**
In the picture the **clients.component.html** is selected, yet the highlighting is not visible (I usually had to set it manually in themes, but I always cannot find it and it needs to be updated on every single IDE when i download this great theme)

Ignore the yellow color, that is correct color for the tests

<img width="349" alt="Screenshot 2024-11-14 at 17 04 01" src="https://github.com/user-attachments/assets/9bd52770-5b21-4b46-967a-69cdedf62131">

**Comment by mallowigi** [comment]
what theme is it?
