### ISSUE TITLE
Folder icon not showing

### ISSUE THREAD

**Issue by EchoLogical** [AtomMaterialUI/a-file-icon-idea#474]
folder icon not working in icon intellij idea 2024.2.5
![image](https://github.com/user-attachments/assets/f446da05-c500-408e-87af-814d0cc1e655)

![image](https://github.com/user-attachments/assets/afd67955-e6ca-48a2-9e52-8e8bc7eada2c)

**Comment by mallowigi** [comment]
Check if you didn't enable hide icons by mistake
